# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Happy Days
email: takushi1969@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  日々の徒然の事象を記載。	     
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://takushi1969.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
